package study.Exception;

class A
{
  void m1() throws ArrayIndexOutOfBoundsException
  {
    System.out.println("In m1 A");
  }
}
